services:
  app:
    build:
      dockerfile: Dockerfile
    image:
      app
    depends_on:
      database:
        condition: service_healthy

  database:
    image:
      postgres

networks:
  main_network:
    driver: brigde
